### ISSUE TITLE
Need help in annotating the tissue section

### ISSUE THREAD

**Issue by requiem116** [simonsfoundation/spatial_transcriptomics_viz#1]
Thanks for sharing the annotation scripts. 
Currently I am processing a set of spatial transcriptome data as the Maniatis et al., Science 364, 89–93 (2019).
I deployed the juypter notebook and tried the examples, but get confused with the tsv and figures files.
How to generate the same input files from spaceranger outputs?
Waiting for your help.

**Comment by tare** [comment]
You might want to check out [Span](https://github.com/tare/span); at least it will show you the format of the input files. The input files were generated by ST Pipeline. All these tools were developed for the pre-Visium ST arrays, and unfortunately, I do not have any experience with Visium data or Space Ranger.

**Comment by requiem116** [comment]
Thanks for your kind help.  I am trying to apply the Span on the spaceranger outputs.
